[package]
name = "rustlex_codegen"
version = "0.3.1"
authors = ["Leo Testard <leo.testard@gmail.com>"]
description = "Syntex extension for RustLex"
homepage = "https://github.com/LeoTestard/rustlex"
repository = "https://github.com/LeoTestard/rustlex"
keywords = [ "lexer", "lexical", "analyser", "generator" ]
license = "MIT"
build = "build.rs"

[lib]
name = "rustlex_codegen"

[features]
with-syntex = ["quasi/with-syntex", "quasi_codegen/with-syntex", "syntex", "syntex_syntax"]

[build-dependencies]
quasi_codegen = { version = "*" }
syntex        = { version = "*", optional = true }

[dependencies]
log = "*"
quasi         = { version = "*" }
syntex        = { version = "*", optional = true }
syntex_syntax = { version = "*", optional = true }
